src/UI/MpManagement.Web/ViewModels/LeaveTypes/CreateLeaveTypeVM.cs
using System.ComponentModel.DataAnnotations;

namespace MpManagement.Web.ViewModels.LeaveTypes
{
	public class CreateLeaveTypeVM
	{
		[Required]
		public string Name { get; set; }

		[Required]
		[Display(Name = "Default Number Of Days")]
		public int DefaultDay { get; set; }
	}
}

src/UI/MpManagement.Web/ViewModels/LeaveTypes/LeaveTypeVM.cs
namespace MpManagement.Web.ViewModels.LeaveTypes
{
	public class LeaveTypeVM : CreateLeaveTypeVM
	{
        public int Id { get; set; }
    }
}

src/UI/MpManagement.Web/Controllers/LeaveTypeController.cs
using Microsoft.AspNetCore.Mvc;
using MpManagement.Web.Contracts;
using MpManagement.Web.ViewModels.LeaveTypes;

namespace MpManagement.Web.Controllers
{
	public class LeaveTypeController : Controller
	{
		private readonly ILeaveTypeService _leaveTypeService;

		public LeaveTypeController(ILeaveTypeService leaveTypeService)
        {
			_leaveTypeService = leaveTypeService;
		}

		[HttpGet]
        public async Task<IActionResult> Index()
		{
			var leaveTypes = await _leaveTypeService.GetLeaveTypes();
			return View(leaveTypes);
		}

        [HttpGet("create-leave-type")]
        public async Task<IActionResult> CreateLeaveType()
        {
            return View();
        }

        [HttpPost("create-leave-type")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateLeaveType(CreateLeaveTypeVM createLeaveType)
        {
			if (ModelState.IsValid)
			{
                var response = await _leaveTypeService.CreateLeaveType(createLeaveType);
                if (response.Success)
                    return RedirectToAction("Index");
                ModelState.AddModelError("Name", response.ValidationErrors);
            }
			return View(createLeaveType);
        }

        [HttpGet("edit-leave-type/{id}")]
        public async Task<IActionResult> EditLeaveType(int id)
        {
            var leaveType = await _leaveTypeService.GetLeaveType(id);
            return View(leaveType);
        }

        [HttpPost("edit-leave-type/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditLeaveType(int id, LeaveTypeVM leaveType)
        {
            if (ModelState.IsValid)
            {
                var response = await _leaveTypeService.UpdateLeaveType(id, leaveType);
                if(response.Success)
                    return RedirectToAction("Index");
                ModelState.AddModelError("Name", response.ValidationErrors);
            }
            return View(leaveType);
        }

        [HttpGet("leave-type/{id}")]
        public async Task<IActionResult> LeaveTypeDetails(int id)
        {
            var leaveType = await _leaveTypeService.GetLeaveType(id);
            return View(leaveType);
        }

        [HttpGet("delete-leave-type/{id}")]
        public async Task<IActionResult> DeleteLeaveType(int id)
        {
            var response = await _leaveTypeService.DeleteLeaveType(id);
            if (response.Success)
                return RedirectToAction("Index");
            else
                return BadRequest();
        }
    }
}

src/UI/MpManagement.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/UI/MpManagement.Web/Views/LeaveType/CreateLeaveType.cshtml
@model MpManagement.Web.ViewModels.LeaveTypes.CreateLeaveTypeVM

@{
    ViewData["Title"] = "CreateLeaveType";
}

<h1>CreateLeaveType</h1>

<h4>LeaveTypeVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateLeaveType">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DefaultDay" class="control-label"></label>
                <input asp-for="DefaultDay" class="form-control" />
                <span asp-validation-for="DefaultDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/UI/MpManagement.Web/Views/LeaveType/EditLeaveType.cshtml
@model MpManagement.Web.ViewModels.LeaveTypes.LeaveTypeVM

@{
    ViewData["Title"] = "EditLeaveType";
}

<h1>EditLeaveType</h1>

<h4>LeaveTypeVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditLeaveType">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DefaultDay" class="control-label"></label>
                <input asp-for="DefaultDay" class="form-control" />
                <span asp-validation-for="DefaultDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/UI/MpManagement.Web/Views/LeaveType/Index.cshtml
@model IEnumerable<MpManagement.Web.ViewModels.LeaveTypes.LeaveTypeVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="CreateLeaveType">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DefaultDay)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DefaultDay)
            </td>
            <td>
                    <a asp-controller="LeaveType" asp-action="EditLeaveType" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="LeaveType" asp-action="LeaveTypeDetails" asp-route-id="@item.Id">Detail</a> |
                    <a asp-controller="LeaveType" asp-action="DeleteLeaveType" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

src/UI/MpManagement.Web/Views/LeaveType/LeaveTypeDetails.cshtml
@model MpManagement.Web.ViewModels.LeaveTypes.LeaveTypeVM

@{
    ViewData["Title"] = "LeaveTypeDetails";
}

<h1>LeaveTypeDetails</h1>

<div>
    <h4>LeaveTypeVM</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DefaultDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DefaultDay)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="LeaveType" asp-action="EditLeaveType" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/UI/MpManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MpManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MpManagement.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MpManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="LeaveType" asp-action="Index">Leave Types</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>